### ISSUE TITLE
Questions: How to make single spa sass prefix?

### ISSUE THREAD

**Issue by ahmetcaglayan** [single-spa/single-spa-css#18]
I apply the following prefix setting for 'sass'. But the output is not what I want. The '/' signs remain. And the text color is not red. Do I need to add another setting? I added the prefix setting as in the document, but I seem to be missing something.

https://single-spa.js.org/docs/ecosystem-css#postcss-prefix-selector

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/13018803/164683359-7a1fcc9b-defd-46de-830f-e6ee02a10e9b.png">
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/13018803/164683435-3ab7a3fc-fc47-4315-8408-87d6646d25f4.png">
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/13018803/164683495-5f015c35-afa9-4883-afab-631e705088cc.png">
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/13018803/164683698-d497f280-066a-4a15-8da3-9145da56082f.png">
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/13018803/164684520-c0d4a21a-3de6-4d8d-a1ca-d5f19ad83e4b.png">

**Comment by ahmetcaglayan** [comment]
it's not working.

prefix: "#single-spa-application:\\@kapital\\/dashboard"

output still has '/' signs.

#single-spa-application:\@kapital\/dashboard .deneme {
    color: red;
}

**Comment by ahmetcaglayan** [comment]
https://github.com/RadValentin/postcss-prefix-selector/issues/106

**Comment by filoxo** [comment]
Very interesting. You might also try using [`CSS.escape`](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape) to properly escape/encode those characters. This is a CSSOM feature though and would need a [polyfill library such as cssesc](https://github.com/mathiasbynens/cssesc) to use in a Node environment, which is the execution environment that that configuration is evaluated in. We [make use of CSS.escape in single-spa-inspector](https://github.com/single-spa/single-spa-inspector/blob/bd6792567f6ead3d98ccd692ac2b1982c2f77676/src/inspected-window-helpers/overlay-helpers.js#L43) to match single-spa's automatically generated selectors so that might be good to reference for an example usage of that API.

**Comment by filoxo** [comment]
Yea I had included an example usage in the previous comment. Did that end up working for you? I might propose moving this over to a Discussion post if you got this working as you intended.

**Comment by ahmetcaglayan** [comment]
The problem is solved with sass module instead of prefix. but after the decision to use mui, we did not have such a problem. We are preparing a very nice application. If you support it, we will share it with you when it is finished. You can add sample applications link to your site. It will be very comprehensive and suitable for large companies.
